from enum import Enum


class CallState(str, Enum):
    INCOMING = "INCOMING"
    ASK_ORIGIN = "ASK_ORIGIN"
    RECORD_ORIGIN = "RECORD_ORIGIN"
    ASK_DESTINATION = "ASK_DESTINATION"
    RECORD_DESTINATION = "RECORD_DESTINATION"
    ASK_NOTES = "ASK_NOTES"
    RECORD_NOTES = "RECORD_NOTES"
    PROCESSING_ORDER = "PROCESSING_ORDER"
    PLAY_SUMMARY = "PLAY_SUMMARY"
    AWAIT_CONFIRMATION = "AWAIT_CONFIRMATION"
    SEARCHING_DRIVER_MESSAGE = "SEARCHING_DRIVER_MESSAGE"
    CONNECT_DRIVER = "CONNECT_DRIVER"
    CONNECT_CUSTOMER = "CONNECT_CUSTOMER"
    FINISHED = "FINISHED"
    FAILED = "FAILED"
