from enum import Enum


class RoutingAction(str, Enum):
    NEW_ORDER = "NEW_ORDER"
    PLAY_SEARCHING_MESSAGE = "PLAY_SEARCHING_MESSAGE"
    CONNECT_TO_DRIVER = "CONNECT_TO_DRIVER"
    CONNECT_TO_CUSTOMER = "CONNECT_TO_CUSTOMER"
    PLAY_NO_ACTIVE_RIDE = "PLAY_NO_ACTIVE_RIDE"
    PLAY_GENERIC_MESSAGE = "PLAY_GENERIC_MESSAGE"
